name: OdinTest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acaba7'
    - '#474f52'
    - '#e8a608'
    - '#bb8715'
    - '#f5fd70'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
